<<<<<<< HEAD
{% set metrics_memory = "200Mi" -%}
{% set eventer_memory = "200Mi" -%}
=======
{% set base_metrics_memory = "140Mi" -%}
{% set metrics_memory = base_metrics_memory -%}
{% set base_metrics_cpu = "80m" -%}
{% set metrics_cpu = base_metrics_cpu -%}
{% set base_eventer_memory = "190Mi" -%}
{% set eventer_memory = base_eventer_memory -%}
{% set metrics_memory_per_node = 4 -%}
{% set metrics_cpu_per_node = 0.5 -%}
{% set eventer_memory_per_node = 500 -%}
>>>>>>> tags/v1.3.0
{% set num_nodes = pillar.get('num_nodes', -1) -%}
{% set nanny_memory = "90Mi" -%}
{% set nanny_memory_per_node = 200 -%}
{% if num_nodes >= 0 -%}
<<<<<<< HEAD
  {% set metrics_memory = (200 + num_nodes * 4)|string + "Mi" -%}
  {% set eventer_memory = (200 * 1024 + num_nodes * 500)|string + "Ki" -%}
=======
  {% set metrics_memory = (200 + num_nodes * metrics_memory_per_node)|string + "Mi" -%}
  {% set metrics_cpu = (80 + num_nodes * metrics_cpu_per_node)|string + "m" -%}
  {% set eventer_memory = (200 * 1024 + num_nodes * eventer_memory_per_node)|string + "Ki" -%}
  {% set nanny_memory = (90 * 1024 + num_nodes * nanny_memory_per_node)|string + "Ki" -%}
>>>>>>> tags/v1.3.0
{% endif -%}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: heapster-v1.0.0
=======
  name: heapster-v1.1.0
>>>>>>> tags/v1.3.0
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.1.0
spec:
  replicas: 1
  selector:
<<<<<<< HEAD
    k8s-app: heapster
=======
    matchLabels:
      k8s-app: heapster
      version: v1.1.0
>>>>>>> tags/v1.3.0
  template:
    metadata:
      labels:
        k8s-app: heapster
<<<<<<< HEAD
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v1.0.0
=======
        version: v1.1.0
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v1.1.0
>>>>>>> tags/v1.3.0
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
<<<<<<< HEAD
              cpu: 100m
              memory: {{ metrics_memory }}
            requests:
              cpu: 100m
=======
              cpu: {{ metrics_cpu }}
              memory: {{ metrics_memory }}
            requests:
              cpu: {{ metrics_cpu }}
>>>>>>> tags/v1.3.0
              memory: {{ metrics_memory }}
          command:
            - /heapster
            - --source=kubernetes.summary_api:''
            - --sink=gcm
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
<<<<<<< HEAD
        - image: gcr.io/google_containers/heapster:v1.0.0
=======
        - image: gcr.io/google_containers/heapster:v1.1.0
>>>>>>> tags/v1.3.0
          name: eventer
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: {{ eventer_memory }}
            requests:
              cpu: 100m
              memory: {{ eventer_memory }}
          command:
            - /eventer
            - --source=kubernetes:''
            - --sink=gcl
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
        - image: gcr.io/google_containers/addon-resizer:1.3
          name: heapster-nanny
          resources:
            limits:
              cpu: 50m
              memory: {{ nanny_memory }}
            requests:
              cpu: 50m
              memory: {{ nanny_memory }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu={{ base_metrics_cpu }}
            - --extra-cpu={{ metrics_cpu_per_node }}m
            - --memory={{ base_metrics_memory }}
            - --extra-memory={{metrics_memory_per_node}}Mi
            - --threshold=5
            - --deployment=heapster-v1.1.0
            - --container=heapster
            - --poll-period=300000
            - --estimator=exponential
        - image: gcr.io/google_containers/addon-resizer:1.3
          name: eventer-nanny
          resources:
            limits:
              cpu: 50m
              memory: {{ nanny_memory }}
            requests:
              cpu: 50m
              memory: {{ nanny_memory }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=100m
            - --extra-cpu=0m
            - --memory={{base_eventer_memory}}
            - --extra-memory={{eventer_memory_per_node}}Ki
            - --threshold=5
            - --deployment=heapster-v1.1.0
            - --container=eventer
            - --poll-period=300000
            - --estimator=exponential
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs"
